services:
  ${NODE_NAME}:
    image: ${IMAGE}:${TAG}
    restart: always
    env_file:
      -  ../../docker-makefiles/${EDGELAKE_TYPE}-configs/base_configs.env
      - ../../docker-makefiles/${EDGELAKE_TYPE}-configs/advance_configs.env
      - ../../docker-makefiles/.env
    container_name: ${NODE_NAME}
    stdin_open: true
    tty: true
    ports:
      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
      - ${MCP_PORT}:${MCP_PORT}
    volumes:
      - ${NODE_NAME}-anylog:/app/EdgeLake/anylog
      - ${NODE_NAME}-blockchain:/app/EdgeLake/blockchain
      - ${NODE_NAME}-data:/app/EdgeLake/data
      - ${NODE_NAME}-local-scripts:/app/deployment-scripts
volumes:
  ${NODE_NAME}-anylog:
  ${NODE_NAME}-blockchain:
  ${NODE_NAME}-data:
  ${NODE_NAME}-local-scripts:
