services:
  ${NODE_NAME}:
    image: ${IMAGE}:${TAG}
    restart: always
    env_file:
      -  ../docker-makefiles/edgelake_${EDGELAKE_TYPE}.env
      - .env
    container_name: ${NODE_NAME}
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ${NODE_NAME}-anylog:/app/EdgeLake/anylog
      - ${NODE_NAME}-blockchain:/app/EdgeLake/blockchain
      - ${NODE_NAME}-data:/app/EdgeLake/data
      - ${NODE_NAME}-local-scripts:/app/deployment-scripts
volumes:
  ${NODE_NAME}-anylog:
  ${NODE_NAME}-blockchain:
  ${NODE_NAME}-data:
  ${NODE_NAME}-local-scripts:
